openapi: "3.0.0"
info:
  version: 1.0.0
  title: Opinion Accounts
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
   /:
      post:
         summary: Create a account
         operationId: createAccount
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/CreateAccountRequest"
         responses:
            '201':
               description: Create Account Result with uid
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/CreateAccountResult"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
  
   /{accountUid}:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Info for a specific account
         operationId: showAccountById
         tags:
           - accounts
         responses:
           '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Account"
           default:
             description: unexpected error
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Error"
      
      put:
         summary: Modify account
         operationId: modifyAccountById
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ModifyAccountRequest"
         responses:
            '204':
               description: Account updated
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      delete:
         summary: Delete account
         operationId: deleteAccountById
         tags:
            - accounts
         responses:
            '204':
               description: Account deleted
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/balance:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Get account balance
         operationId: showAccountBalanceById
         tags:
            - accounts
         responses:
            '200':
               description: Account balance
               content:
                  application/json:
                     schema:
                        type: number
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      post:
         summary: Change account balance
         operationId: changeAccountBalance
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ChangeBalanceRequest"
         responses:
            '204':
               description: Account balance changed
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/owner:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Change account owner
         operationId: changeAccountOwner
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ChangeOwnerRequest"
         responses:
            '204':
               description: Account owner changed
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   
   /{accountUid}/users:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Attach account user
         operationId: attachAccountUser
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/AccountUserAssociationRequest"
         responses:
            '204':
               description: Account user attached
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      delete:
         summary: Detach account user
         operationId: detachAccountUser
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/AccountUserAssociationRequest"
         responses:
            '204':
               description: Account user detached
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   
   /{accountUid}/service-package:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Change account service package
         operationId: changeAccountServicePackage
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ChangeServicePackageRequest"
         responses:
            '204':
               description: Account service package changed
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/business-details:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Get account business details
         operationId: getAccountBusinessDetails
         tags:
            - accounts
         responses:
            '200':
               description: Account business details
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/AccountBusinessDetails"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /_search:
      post:
         summary: Search accounts
         operationId: searchAccounts
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchAccountsRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/SearchResult"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /_search/by-user-product:
      post:
         summary: Find accounts by user and product
         operationId: findAccountsByUserProduct
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchByUserProductRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /_search/by-service-package-expiry:
      post:
         summary: Find accounts by service package expiry
         operationId: findAccountsByServicePackageExpire
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchByServicePackageExpiryRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /status:
      get:
         summary: Service status
         operationId: status
         tags:
            - accounts
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                  schema:
                     type: object
   /_probe:ping:
      post:
         summary: Probe ping
         operationId: probePing
         tags:
            - accounts
         responses:
            '204':
               description: Probe accepted
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      
components:
   schemas:
      CreateAccountRequest:
         description:  CreateAccountRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            name:
               type: string
            client_ip:
               type: string
            country_id:
               type: number
            source_id:
               type: number
            service_package_id:
               type: number
            bo_user_id:
               type: number
      
      CreateAccountResult:
         description: CreateAccountResult
         required:
            - uid
         properties:
            uid:
               type: string
            id:
               type: number
            
      SearchAccountsRequest:   
         description:  SearchAccountsRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            include_non_active:
               type: boolean
            top:
               type: number
            from:
               description: date-time
               type: string
               format: date-time
            to:
               description: date-time
               type: string
               format: date-time
            ids:
               type: array
               items:
                  type: number
            expiry_at:
               description: date-time
               type: string
               format: date-time

      SearchByUserProductRequest:
         description: SearchByUserProductRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number

      SearchByServicePackageExpiryRequest:
         description: SearchByServicePackageExpiryRequest
         required:
            - expiry_at
         properties:
            expiry_at:
               description: date-time
               type: string
               pattern: '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s(0?[1-9]|[12][0-9]|3[01]),\s\d{4}\s([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'
            
      Account:
         required:
            - uid
         properties:
            uid:
               type: string
            id:
               type: number
            service_package_id:
               type: number
            service_package_name:
               type: string
            product_id:
               type: number
            name:
               type: string
            details:
               type: string
            owner_id:
               type: number
            timezone:
               type: string
            created_at:
               type: string
               format: date-time
            updated_at:
               type: string
               format: date-time
            active:
               type: boolean
            status_id:
               type: number
            balance:
               type: number
            supply_days_interval:
               type: number
            next_supply_sessions_credit:
               type: number
            last_sessions_credited_at:
               type: string
            timezone_offset:
               type: number
            max_users:
               type: number
            min_deposit_amount:
               type: number
            max_deposit_amount:
               type: number
            details:
               type: string

      ModifyAccountRequest:
         description: ModifyAccountRequest
         properties:
            timezone_id:
               type: number
            name:
               type: string
            is_active:
               type: boolean
            owner_id:
               type: number
            include_deposit_bounds:
               type: boolean
            min_deposit_amount:
               type: number
            max_deposit_amount:
               type: number
            details:
               type: string
            business_company_name:
               type: string
            business_first_name:
               type: string
            business_last_name:
               type: string
            business_address1:
               type: string
            business_address2:
               type: string
            business_city:
               type: string
            business_country_id:
               type: number
            business_state_id:
               type: number
            business_postal_code:
               type: string
            business_phone1:
               type: string

      ChangeBalanceRequest:
         description: ChangeBalanceRequest
         required:
            - bo_user_id
            - amount
            - operation_type_id
            - source_id
         properties:
            bo_user_id:
               type: number
            details:
               type: string
            amount:
               type: number
            operation_type_id:
               type: number
            source_id:
               type: number
            session_id:
               type: string
            geo_country_code:
               type: string
            client_ip:
               type: string

      ChangeOwnerRequest:
         description: ChangeOwnerRequest
         required:
            - source_id
            - owner_id
            - bo_user_id
         properties:
            source_id:
               type: number
            owner_id:
               type: number
            bo_user_id:
               type: number

      AccountUserAssociationRequest:
         description: AccountUserAssociationRequest
         required:
            - source_id
            - user_id
            - bo_user_id
         properties:
            source_id:
               type: number
            user_id:
               type: number
            bo_user_id:
               type: number

      ChangeServicePackageRequest:
         description: ChangeServicePackageRequest
         required:
            - service_package_id
            - expiry_at
            - max_users
         properties:
            service_package_id:
               type: number
            expiry_at:
               description: date-time
               type: string
               pattern: '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s(0?[1-9]|[12][0-9]|3[01]),\s\d{4}\s([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'
            max_users:
               type: number

      AccountBusinessDetails:
         description: AccountBusinessDetails
         properties:
            business_company_name:
               type: string
            business_first_name:
               type: string
            business_last_name:
               type: string
            business_address1:
               type: string
            business_address2:
               type: string
            business_city:
               type: string
            business_country_id:
               type: number
            business_state_id:
               type: number
            business_postal_code:
               type: string
            business_phone1:
               type: string
        
      Accounts:
         type: array
         items:
            $ref: "#/components/schemas/Account"
      
      SearchResult:
         description: SearchResult
         properties:
            items:
               $ref: "#/components/schemas/Accounts"
            size:
               type: number
      Error:
         required:
            - code
            - detail
            - status
         properties:
            code:
               type: string
            detail:
               type: string
            status:
               type: number
