openapi: "3.0.0"
info:
  version: 1.0.0
  title: Opinion Accounts
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
   /:
      post:
         summary: Create a account
         operationId: createAccount
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/CreateAccountRequest"
         responses:
            '201':
               description: Create Account Result with uid
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/CreateAccountResult"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
  
   /{accountUid}:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Info for a specific account
         operationId: showAccountById
         tags:
           - accounts
         responses:
           '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Account"
           default:
             description: unexpected error
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Error"
      
      put:
         summary: Modify account
         operationId: modifyAccountById
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ModifyAccountDetailsRequest"
         responses:
            '204':
               description: Account updated
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      delete:
         summary: Delete account
         operationId: deleteAccountById
         tags:
            - accounts
         responses:
            '204':
               description: Account deleted
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/balance:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Get account balance
         operationId: showAccountBalanceById
         tags:
            - accounts
         responses:
            '200':
               description: Account balance
               content:
                  application/json:
                     schema:
                        type: number
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      post:
         summary: Change account balance
         operationId: changeAccountBalance
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ChangeBalanceRequest"
         responses:
            '204':
               description: Account balance changed
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/owner:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Change account owner
         operationId: changeAccountOwner
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ChangeOwnerRequest"
         responses:
            '204':
               description: Account owner changed
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/users:attach:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Attach account user
         operationId: attachAccountUser
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/AccountUserAssociationRequest"
         responses:
            '204':
               description: Account user attached
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /{accountUid}/users:detach:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      post:
         summary: Detach account user
         operationId: detachAccountUser
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/AccountUserAssociationRequest"
         responses:
            '204':
               description: Account user detached
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /_search:
      post:
         summary: Search accounts
         operationId: searchAccounts
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchAccountsRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/SearchResult"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /_search/by-user-product:
      post:
         summary: Find accounts by user and product
         operationId: findAccountsByUserProduct
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchByUserProductRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"

   /_search/by-service-package-expiry:
      post:
         summary: Find accounts by service package expiry
         operationId: findAccountsByServicePackageExpire
         tags:
            - accounts
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchByServicePackageExpiryRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /status:
      get:
         summary: Service status
         operationId: status
         tags:
            - accounts
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                  schema:
                     type: object
      
components:
   schemas:
      CreateAccountRequest:
         description:  CreateAccountRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            name:
               type: string
            client_ip:
               type: string
            country_id:
               type: number
            source_id:
               type: number
            service_package_id:
               type: number
            bo_user_id:
               type: number
      
      CreateAccountResult:
         description: CreateAccountResult
         required:
            - uid
         properties:
            uid:
               type: string
            id:
               type: number
            
      SearchAccountsRequest:   
         description:  SearchAccountsRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            include_non_active:
               type: boolean
            top:
               type: number
            from:
               description: date-time
               type: string
               format: date-time
            to:
               description: date-time
               type: string
               format: date-time
            ids:
               type: array
               items:
                  type: number
            expiry_at:
               description: date-time
               type: string
               format: date-time

      SearchByUserProductRequest:
         description: SearchByUserProductRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number

      SearchByServicePackageExpiryRequest:
         description: SearchByServicePackageExpiryRequest
         required:
            - expiry_at
         properties:
            expiry_at:
               description: date-time
               type: string
               format: date-time
            
      Account:
         required:
            - uid
         properties:
            uid:
               type: string
            name:
               type: string

      ModifyAccountDetailsRequest:
         description: ModifyAccountDetailsRequest
         properties:
            comments:
               type: string
            timezone_id:
               type: number
            account_name:
               type: string
            is_active:
               type: boolean
            owner_id:
               type: number
            include_deposit_bounds:
               type: boolean
            min_deposit_amount:
               type: number
            max_deposit_amount:
               type: number

      ChangeBalanceRequest:
         description: ChangeBalanceRequest
         required:
            - bo_user_id
            - amount
            - accop_type_id
         properties:
            bo_user_id:
               type: number
            comments:
               type: string
            amount:
               type: number
            accop_type_id:
               type: number
            source_guid:
               type: string
            session_id:
               type: string
            geo_country_code:
               type: string
            client_ip:
               type: string

      ChangeOwnerRequest:
         description: ChangeOwnerRequest
         required:
            - source_id
            - owner_id
            - bo_user_id
         properties:
            source_id:
               type: number
            owner_id:
               type: number
            bo_user_id:
               type: number

      AccountUserAssociationRequest:
         description: AccountUserAssociationRequest
         required:
            - source_id
            - user_id
            - bo_user_id
         properties:
            source_id:
               type: number
            user_id:
               type: number
            bo_user_id:
               type: number
        
      Accounts:
         type: array
         items:
            $ref: "#/components/schemas/Account"
      
      SearchResult:
         description: SearchResult
         properties:
            items:
               $ref: "#/components/schemas/Accounts"
            size:
               type: number
      Error:
         required:
            - code
            - detail
            - status
         properties:
            code:
               type: string
            detail:
               type: string
            status:
               type: number
