openapi: "3.0.0"
info:
  version: 1.0.0
  title: Opinion Accounts
  license:
    name: MIT
servers:
  - url: http://localhost:8080
paths:
   /:
      get:
         summary: List all accounts
         operationId: listAccounts
         tags:
            - accounts
         responses:
            '200':
               description: A paged array of accounts
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      post:
         summary: Create a account
         operationId: createAccount
         tags:
            - accounts
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/CreateAccountRequest"
         responses:
            '201':
               description: Create Account Result with uid
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
  
   /{accountUid}:
      parameters:
         - name: accountUid
           in: path
           required: true
           description: The uid of the account to retrieve
           schema:
             type: string
      get:
         summary: Info for a specific account
         operationId: showAccountById
         tags:
           - accounts
         responses:
           '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
           default:
             description: unexpected error
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Error"
      
      put:
         summary: Modify account
         operationId: modifyAccountById
         tags:
            - accounts
         responses:
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
      delete:
         summary: Delete account
         operationId: deleteAccountById
         tags:
            - accounts
         responses:
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /_search:
      post:
         summary: Search accounts
         operationId: searchAccounts
         tags:
            - accounts
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/SearchAccountsRequest"
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                 schema:
                   $ref: "#/components/schemas/Accounts"
            default:
               description: unexpected error
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/Error"
   /status:
      get:
         summary: Service status
         operationId: status
         tags:
            - accounts
         responses:
            '200':
             description: Expected response to a valid request
             content:
               application/json:
                  schema:
                     type: object
      
components:
   schemas:
      CreateAccountRequest:
         description:  CreateAccountRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            name:
               type: string
            client_ip:
               type: string
            country_id:
               type: number
            source_id:
               type: number
            service_package_id:
               type: number
            bo_user_id:
               type: number
            
      SearchAccountsRequest:   
         description:  SearchAccountsRequest
         required:
            - user_id
            - product_id
         properties:
            user_id:
               type: number
            product_id:
               type: number
            include_non_active:
               type: boolean
            top:
               type: number
            from:
               description: date-time
               type: string
               format: date-time
            to:
               description: date-time
               type: string
               format: date-time
            
      Account:
         required:
            - uid
         properties:
            uid:
               type: string
            name:
               type: string
        
      Accounts:
         type: array
         items:
            $ref: "#/components/schemas/Account"
      Error:
         required:
            - code
            - detail
            - status
         properties:
            code:
               type: string
            detail:
               type: string
            status:
               type: number
